export function launchpadHtml(nonce: string): string {
  return `<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}';">
  <style nonce="${nonce}">
  *{box-sizing:border-box}body{margin:0;color:var(--vscode-foreground);background:var(--vscode-editor-background);font:13px var(--vscode-font-family)}header{display:flex;gap:8px;align-items:center;padding:12px 16px;border-bottom:1px solid var(--vscode-panel-border)}h1{font-size:20px;margin:0;flex:1}button,select{color:var(--vscode-button-foreground);background:var(--vscode-button-background);border:0;border-radius:3px;padding:6px 10px;font:inherit;cursor:pointer}.secondary{color:var(--vscode-button-secondaryForeground);background:var(--vscode-button-secondaryBackground)}main{max-width:1100px;margin:auto;padding:18px}.notice{padding:10px;border:1px solid var(--vscode-panel-border);margin-bottom:14px;color:var(--vscode-descriptionForeground)}section{margin:20px 0}h2{font-size:14px;text-transform:uppercase;color:var(--vscode-descriptionForeground)}.card{display:grid;grid-template-columns:70px 1fr auto;gap:10px;align-items:center;padding:11px;border:1px solid var(--vscode-panel-border);margin:6px 0}.card:hover{background:var(--vscode-list-hoverBackground)}.number{font-family:var(--vscode-editor-font-family);color:var(--vscode-textLink-foreground)}.title{font-weight:600}.meta,.empty{color:var(--vscode-descriptionForeground);font-size:11px}.labels{display:inline-flex;gap:4px;margin-left:6px}.label{border:1px solid var(--vscode-badge-background);border-radius:8px;padding:0 5px}.actions{display:flex;gap:5px}.draft{opacity:.7}
  </style></head><body><header><h1>Launchpad</h1><span id="account"></span><button id="connect" class="secondary">Connect GitHub</button><button id="refresh" class="secondary">Refresh</button></header><main><div class="notice">Optional provider view. Public GitHub repositories work without an account; connecting enables private repositories and personalized categories.</div><div id="content"><div class="empty">Loading pull requests…</div></div></main>
  <script nonce="${nonce}">
  const vscode=acquireVsCodeApi(),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function card(item,index){return'<div class="card '+(item.draft?'draft':'')+'"><span class="number">'+esc(item.repository)+' #'+item.number+'</span><div><div class="title">'+esc(item.title)+'</div><div class="meta">'+esc(item.author)+' · '+esc(item.head)+' → '+esc(item.base)+' · '+new Date(item.updatedAt).toLocaleString()+(item.draft?' · Draft':'')+'<span class="labels">'+item.labels.map(label=>'<span class="label">'+esc(label)+'</span>').join('')+'</span></div></div><div class="actions"><button data-changes="'+index+'">Changes</button><button data-open="'+index+'" class="secondary">Open</button><button data-checkout="'+index+'" class="secondary">Checkout</button></div></div>'}
  function render(model){document.getElementById('account').textContent=model.account||'Public mode';document.getElementById('connect').textContent=model.account?'Switch Account':'Connect GitHub';const groups=[['Current Branch',item=>item.currentBranch],['Needs My Review',item=>!item.currentBranch&&item.reviewRequested],['My Pull Requests',item=>!item.currentBranch&&!item.reviewRequested&&item.mine],['Other Open',item=>!item.currentBranch&&!item.reviewRequested&&!item.mine]];document.getElementById('content').innerHTML=(model.warning?'<div class="notice">'+esc(model.warning)+'</div>':'')+groups.map(([title,predicate])=>{const items=model.items.map((item,index)=>({item,index})).filter(entry=>predicate(entry.item));return'<section><h2>'+title+' ('+items.length+')</h2>'+(items.map(entry=>card(entry.item,entry.index)).join('')||'<div class="empty">None</div>')+'</section>'}).join('');document.querySelectorAll('[data-changes]').forEach(button=>button.addEventListener('click',()=>vscode.postMessage({type:'changes',index:Number(button.dataset.changes)})));document.querySelectorAll('[data-open]').forEach(button=>button.addEventListener('click',()=>vscode.postMessage({type:'open',index:Number(button.dataset.open)})));document.querySelectorAll('[data-checkout]').forEach(button=>button.addEventListener('click',()=>vscode.postMessage({type:'checkout',index:Number(button.dataset.checkout)})))}
  document.getElementById('connect').addEventListener('click',()=>vscode.postMessage({type:'connect'}));document.getElementById('refresh').addEventListener('click',()=>vscode.postMessage({type:'refresh'}));window.addEventListener('message',event=>{if(event.data.type==='model')render(event.data);if(event.data.type==='error')document.getElementById('content').innerHTML='<div class="notice">'+esc(event.data.message)+'</div>'});vscode.postMessage({type:'ready'});
  </script></body></html>`;
}
